config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :confirmation => "users/confirmations",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :unlocks => "users/unlocks",
      :omniauth_callbacks => "users/omniauth_callbacks"
  }

  devise_scope :user do
    get "sign_in" => "users/sessions#new"
    get "sign_up" => "users/registrations#new"
    get "sign_out" => "users/sessions#destroy"
    get "change_password" => "users/registrations#change_password"
    post "update_password" => "users/registrations#update_password"
    get "/super_admin" => "users/sessions#super_admin_new"
  end

  root :to => "home#index"

  resources :home

  namespace :super_admin do
    resources :dashboard
    resources :categories
    resources :sub_categories
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, :as => :parent, :class_name => "Category", :dependent => :destroy
  validates :name, :presence => true
  belongs_to :parent, :polymorphic => true

end

app/controllers/super_admin/categories_controller.rb
class SuperAdmin::CategoriesController < SuperAdmin::SuperAdminController
  add_breadcrumb "CATEGORIES", "/super_admin/categories"
  layout "super_admin"

  def index
    @categories = Category.where(:parent_id => nil)

  end

  def new
    @category = Category.new
    #render :layout => false
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully Added."
      render :json => {:success => true, :url => super_admin_categories_path}.to_json
    else
      @errors = @category.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
    #render :layout => false
  end

  def update
    @category = Category.find_by_id(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Category was successfully Added."
      render :json => {:success => true, :url => super_admin_categories_path}.to_json
    else
      @category = @user.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def category_params
    params.require(:category).permit(:name, :parent_id, :parent_type)
  end


end

app/controllers/super_admin/dashboard_controller.rb
class SuperAdmin::DashboardController < SuperAdmin::SuperAdminController
  #before_filter :set_partner, :except => [:create]
  #layout "super_admin"

  def index
    @stores = User.merchants.size
    @new_stores = User.merchants.where("Date(users.created_at) > ?", Date.today - 7.day).size
    @customers = User.customers.size
    @new_customers = User.customers.where("Date(users.created_at) > ?", Date.today - 7.day).size
    @customers = User.all
  end

end

app/controllers/super_admin/home_controller.rb
class SuperAdmin::HomeController < SuperAdmin::SuperAdminController

  def index
    redirect_to super_admin_categories_path
  end

end

app/controllers/super_admin/merchants_controller.rb
class SuperAdmin::MerchantsController < SuperAdmin::SuperAdminController

  #add_breadcrumb "STORE OWNERS", "/super_admin/merchants"

  layout "super_admin"

  def index
    @merchants = User.merchants.sort_by { |u| u.id }
  end

  def new
    @user= User.new
    #render :layout => false
  end

  def show
    user = User.find_by_id(params[:id])
    @merchant = user
    render :layout => false
  end


  def create
    unless params[:user][:date_of_birth].blank?
      time = Time.strptime(params[:user][:date_of_birth], '%m-%d-%Y')
      params[:user][:date_of_birth] = time.strftime("%Y/%m/%d")
    end
    @user = User.new(merchant_params)
    @user.roles << Role.find_by_name("merchant")
    if @user.valid? and register_merchant
      if @user.save
        seed_shop_hours(@user.shop)
        flash[:notice] = "Merchant was successfully Added."
        render :json => {:success => true, :url => super_admin_merchants_path}.to_json
      else
        @errors = @user.errors
        render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      end
    else
      @errors = @user.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def register_merchant
    phone_number = nil
    unless params[:user][:shop_attributes][:phone].blank?
      phone_number = params[:user][:shop_attributes][:phone].gsub("-", "")
    end
    @result = Braintree::MerchantAccount.create(
        :individual => {
            :first_name => @user.name,
            :last_name => @user.name,
            :email => @user.email,
            :phone => phone_number,
            :date_of_birth => params[:user][:date_of_birth],
            #:ssn => "456-45-4567",
            :address => {
                :street_address => params[:user][:shop_attributes][:address],
                :locality => params[:user][:shop_attributes][:city],
                :region => params[:user][:shop_attributes][:state],
                :postal_code => params[:user][:shop_attributes][:zip_code]
            }
        },
        :funding => {
            :destination => Braintree::MerchantAccount::FundingDestination::Bank,
            :email => @user.email,
            :mobile_phone => phone_number,
            :account_number => params[:account_number],
            :routing_number => params[:routing_number]
        },
        :tos_accepted => true,
        :master_merchant_account_id => "3fsj28htzdwyh7dh"
    #:id => "blue_ladders_store"
    )
    if @result.success?
      @user.customer_id = @result.merchant_account.id
      return true
    else
      @brain_errors = @result.errors
      @result.errors.each { |error| @user.errors.add(" ", error.message) }
      return false
    end
  end


  def edit
    @user = User.find_by_id(params[:id])
    #render :layout => false
  end

  def update
    @user = User.find_by_id(params[:id])
    #if @user.update_attributes(merchant_params)
    #  flash[:notice] = "Merchant was successfully Added."
    #  render :json => {:success => true, :url => super_admin_merchants_path}.to_json
    #else
    #  @errors = @user.errors
    #  render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    #end
    unless params[:user][:date_of_birth].blank?
      time = Time.strptime(params[:user][:date_of_birth], '%m-%d-%Y')
      params[:user][:date_of_birth] = time.strftime("%Y/%m/%d")
    end
    if update_merchant_bank_account
      puts "CCCC"
      successfully_updated = if needs_password?(@user, params)
                               @user.update(merchant_params)
                             else
                               params[:user].delete(:password)
                               @user.update_without_password(merchant_params)
                             end
      if successfully_updated
        flash[:notice] = "Merchant was successfully Added."
        render :json => {:success => true, :url => super_admin_merchants_path}.to_json
      else
        @errors = @user.errors
        render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      end
    else
      @errors = @user.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def update_merchant_bank_account
    phone_number = nil
    unless params[:user][:shop_attributes][:phone].blank?
      phone_number = params[:user][:shop_attributes][:phone].gsub("-", "")
    end
    merchant = User.find_by_id(@user.id)
    result = Braintree::MerchantAccount.update(
        merchant.customer_id,
        :individual => {
            :first_name => params[:user][:name],
            :last_name => params[:user][:name],
            :email => params[:user][:email],
            :phone => phone_number,
            :date_of_birth => params[:user][:date_of_birth],
            :address => {
                :street_address => params[:user][:shop_attributes][:address],
                :locality => params[:user][:shop_attributes][:city],
                :region => params[:user][:shop_attributes][:state],
                :postal_code => params[:user][:shop_attributes][:zip_code]
            }
        },
        :funding => {
            :destination => Braintree::MerchantAccount::FundingDestination::Bank,
            :email => params[:user][:email],
            :mobile_phone => phone_number,
            :account_number => params[:account_number],
            :routing_number => params[:routing_number]
        })
    if result.success?
      return true
    else
      #@brain_errors = result.errors
      #render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      #return false
      @brain_errors = result.errors
      result.errors.each { |error| @user.errors.add(" ", error.message) }
      return false
    end
  end


  def disable_merchant
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(:status => params[:status])
      @merchants = User.merchants
      render :partial => "super_admin/merchants/list"
    end
  end


#def merchant_params
#  params.require(:merchant).permit(:name, :parent_id, :parent_type)
#end

  private

  def seed_shop_hours(shop)
    start_time = "8:00 am"
    end_time = "07:00 pm"
    ShopHour.create!(:shop_id => shop.id, :name => 'MONDAY', :start_time => start_time, :end_time => end_time, :is_open => true)
    ShopHour.create!(:shop_id => shop.id, :name => 'TUESDAY', :start_time => start_time, :end_time => end_time, :is_open => true)
    ShopHour.create!(:shop_id => shop.id, :name => 'WEDNESDAY', :start_time => start_time, :end_time => end_time, :is_open => true)
    ShopHour.create!(:shop_id => shop.id, :name => 'THURSDAY', :start_time => start_time, :end_time => end_time, :is_open => true)
    ShopHour.create!(:shop_id => shop.id, :name => 'FRIDAY', :start_time => start_time, :end_time => end_time, :is_open => true)
    ShopHour.create!(:shop_id => shop.id, :name => 'SATURDAY', :start_time => start_time, :end_time => end_time, :is_open => true)
    ShopHour.create!(:shop_id => shop.id, :name => 'SUNDAY', :start_time => start_time, :end_time => end_time, :is_open => false)
  end

  def needs_password?(user, params)
    params[:user][:password].present?
  end

  def merchant_params
    params.require(:user).permit(:current_password, :id, :name, :email, :customer_id, :code, :city, :state, :zip, :country, :address, :phone, :zip, :date_of_birth, :password, :password_confirmation, shop_attributes: [:id, :user_id, :name, :phone, :address, :status, :hours, :city, :state, :zip_code, :country])
  end


end

app/controllers/super_admin/profiles_controller.rb
class SuperAdmin::ProfilesController < SuperAdmin::SuperAdminController

  before_filter :authenticate_user!

  layout "super_admin"

  def profile
    @user = current_user
  end

  def update
    @user = User.find_by_id(current_user.id)
    successfully_updated = if needs_password?(@user, params)
                             @user.update(user_params)
                           else
                             params[:user].delete(:password)
                             @user.update_without_password(user_params)
                           end
    if successfully_updated
      flash[:notice] = "Super Admin was successfully Updated."
      render :json => {:success => true, :url => super_admin_customers_path}.to_json
    else
      @errors = @user.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  private

  def needs_password?(user, params)
    params[:user][:password].present?
  end

  def user_params
    params.require(:user).permit(:registration_id, :current_password, :id, :name, :email, :phone, :password, :password_confirmation, asset_attributes: [:id, :owner_id, :owner_type, :owner, :avatar, :avatar_file_name, :avatar_content_type, :avatar_file_size])
  end


end

app/controllers/super_admin/sub_categories_controller.rb
class SuperAdmin::SubCategoriesController < SuperAdmin::SuperAdminController
  add_breadcrumb "SUB CATEGORIES", "/super_admin/sub_categories"
  layout "super_admin"

  def index
    @sub_categories = Category.where("parent_id IS NOT NULL")
  end

  def new
    @category = Category.new
    #render :layout => false
  end

  def create
    @category = Category.new(category_params)
    unless params[:category][:parent_id].blank?
      if @category.save
        flash[:notice] = "Sub Category was successfully Added."
        render :json => {:success => true, :url => super_admin_sub_categories_path}.to_json
      else
        @errors = @category.errors
        render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      end
    else
      @category.errors.add(:parent_category, "Can't be Blank")
      @errors = @category.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def update
    @category = Category.find_by_id(params[:id])
    unless params[:category][:parent_id].blank?
      if @category.update_attributes(category_params)
        flash[:notice] = "Category was successfully Added."
        render :json => {:success => true, :url => super_admin_sub_categories_path}.to_json
      else
        @category = @user.errors
        render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      end
    else
      @category.errors.add(:Parent_category, "Can't be Blank")
      @errors = @category.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
    #render :layout => false
  end

  def category_params
    params.require(:category).permit(:name, :parent_id, :parent_type)
  end


end

app/controllers/super_admin/super_admin_controller.rb
class SuperAdmin::SuperAdminController < ApplicationController

  before_filter :authenticate_user!

  before_filter do
    redirect_to root_url unless current_user.super_admin?
  end

end

app/views/super_admin/categories/_form.html.erb
<div class="row" id="errors"></div>
<section class="g_inputs_phold" style="float: left;width: 48%; margin: 30px 0px">

  <div class="g_inputitem">
    <%= f.text_field :name, :placeholder => "CATEGORY NAME" %>
  </div>
</section>

<!--g_inputs_phold ends-->
<div class="g_popup_head_bot"></div>
<!--g_popup_head ends-->
<div class="g_popup_bot_btns">
  <div class="pl_btn1" id="cancel-btn">
    <a href="javascript:void(0);">CANCEL</a>
  </div>
  <!--pl_btn1 ends-->
  <div class="p2_btn1" id="save-btn">
    <a href="javascript:void(0);">SAVE CHANGES</a>
  </div>
  <!--p2_btn1 ends-->
</div>

app/views/super_admin/categories/_list.html.erb
<table class="table table-striped table-bordered table-hover" id="category_table">
  <thead>
  <tr>
    <th>
      Name
    </th>
    <th>
      Sub Category Count
    </th>
    <th>
      Category Item Count
    </th>
    <th>
      Created
    </th>
    <th style="width: 120px">
      Action
    </th>
  </tr>
  </thead>
  <% unless @categories.blank? %>
      <tbody>
      <% @categories.each_with_index do |category, index| %>
          <tr class="odd gradeX">

            <td>
              <%= category.name %>
            </td>
            <td>
              <%= category.sub_categories.size %>
            </td>
            <% count = 0 %>
            <% category.sub_categories.each do |category| %>
                <% count += category.items.size %>
            <% end %>
            <td class="center">
              <%= count %>
            </td>
            <td class="center">
              <%= category.created_at.strftime("%m-%d-%Y  %H:%M:%S %p") %>
            </td>
            <td>
              &nbsp;&nbsp;&nbsp;
              <%= link_to "Edit", edit_super_admin_category_path(category.id), :style => "text-decoration:none" %>
              &nbsp;&nbsp;&nbsp;

              <%= link_to "View", super_admin_category_path(category.id), :style => "text-decoration:none" %>
            </td>
          </tr>
      <% end %>
      </tbody>
  <% end %>
</table>

app/views/super_admin/categories/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
      Manage Categories
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="/super_admin/dashboard">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="/super_admin/customers">Categories</a>
      </li>

    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
  <div class="col-md-6 ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i> Edit Categories
        </div>
        <div class="tools">
          <a class="collapse" href="">
          </a>

        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for(@category, :url => {:controller => "super_admin/categories", :action => "update"}, :method => "put") do |f| %>
            <%= f.hidden_field :status, :value => "active" %>
            <div class="form-body">
              <div class="row" id="errors"></div>

              <div class="form-group">
                <label>Name</label>

                <div class="input-group">
                  <%= f.text_field :name, :autofocus => true, :class => "form-control", :placeholder => "Name" %>
                </div>
              </div>
            </div>
            <div class="form-actions">
              <div class="z_100" id="save-btn">
                <a class="btn blue" href="javascript:void(0)">Save</a>
              </div>
              <!--<button class="btn blue" type="submit">Update</button>-->
              <%#= f.submit "Save", :class => "btn blue" %>
            </div>
        <% end %>
      </div>
    </div>
    <!-- END SAMPLE FORM PORTLET-->

  </div>
</div>

<div class="clearfix">
</div>

</div>


<script type="text/javascript">

    $(document).ready(function () {

        var placeholder = " ";
        $("input[type=text],input[type=email],input[type=password]").focus(function () {
            placeholder = $(this).attr("placeholder");
            return $(this).attr("placeholder", " ");
        });
        $("input[type=text],input[type=email],input[type=password]").blur(function () {
            if ($(this).val() === "") {
                return $(this).attr("placeholder", placeholder);
            }
        });


        $("#save-btn").children("a").click(function () {
            $("#ajax_loader").show();
            $(".shadow").show();
            $.post($(this).parents("form").attr("action"), $(this).parents("form").serialize(), (function (response) {
                if (response.success) {
                    window.location.href = response.url
                } else {
                    $("#errors").html(response.html);
                    $("#ajax_loader").hide();
                    $(".shadow").hide();
                }

            }), "json");
            return false;

        });

    });


</script>

app/views/super_admin/categories/index.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
      Categories
      <small>Edit , View and More</small>
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="/super_admin/dashboard">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="/super_admin/customers">All Categories</a>
        <!--<i class="fa fa-angle-right"></i>-->
      </li>
    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box grey-cascade">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-globe"></i>Current Categories
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
          <a href="#portlet-config" data-toggle="modal" class="config">
          </a>
          <a href="javascript:;" class="reload">
          </a>
          <a href="javascript:;" class="remove">
          </a>
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-toolbar">
          <div class="btn-group">
            <%= link_to(new_super_admin_category_path) do %>
                <button id="sample_editable_1_new" class="btn green">
                  Add New <i class="fa fa-plus"></i>
                </button>
            <% end %>
          </div>

        </div>
        <div id="customer_lis">
          <%= render :partial => "super_admin/categories/list" %>
        </div>
      </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
  </div>
</div>

<!-- END PAGE CONTENT-->
</div>
</div>


<script>
    jQuery(document).ready(function () {
        TableManaged.init();
        initialize_table();
    });

    function initialize_table() {
        var active_table = $('#category_table');

        // begin first table
        active_table.dataTable({
            "columns": [
                {
                    "orderable": true
                },
                {
                    "orderable": true
                },
                {
                    "orderable": true
                },
                {
                    "orderable": true
                },
                {
                    "orderable": false
                }


            ],
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 5,
            "pagingType": "bootstrap_full_number",
            "language": {
                "lengthMenu": "_MENU_ records",
                "paginate": {
                    "previous": "Prev",
                    "next": "Next",
                    "last": "Last",
                    "first": "First"
                }
            },
            "columnDefs": [
                {  // set default column settings
                    'orderable': false,
                    'targets': [0]
                },
                {
                    "searchable": false,
                    "targets": [0]
                }
            ],
            "order": [
                [1, "asc"]
            ] // set first column as a default sort by asc
        });

    }


</script>

app/views/super_admin/categories/new.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
      Manage Categories
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="/super_admin/dashboard">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="/super_admin/customers">Categories</a>
      </li>

    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
  <div class="col-md-6 ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i> Create New Categories
        </div>
        <div class="tools">
          <a class="collapse" href="">
          </a>

        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for(@category, :url => {:controller => "super_admin/categories", :action => "create"}, :method => "post") do |f| %>
            <%= f.hidden_field :status, :value => "active" %>
            <div class="form-body">
              <div class="row" id="errors"></div>

              <div class="form-group">
                <label>Name</label>

                <div class="input-group">
                  <%= f.text_field :name, :autofocus => true, :class => "form-control", :placeholder => "Name" %>
                </div>
              </div>
            </div>
            <div class="form-actions">
              <div class="z_100" id="save-btn">
                <a class="btn blue" href="javascript:void(0)">Save</a>
              </div>
              <!--<button class="btn blue" type="submit">Update</button>-->
              <%#= f.submit "Save", :class => "btn blue" %>
            </div>
        <% end %>
      </div>
    </div>
    <!-- END SAMPLE FORM PORTLET-->

  </div>
</div>

<div class="clearfix">
</div>

</div>


<script type="text/javascript">

    $(document).ready(function () {

        var placeholder = " ";
        $("input[type=text],input[type=email],input[type=password]").focus(function () {
            placeholder = $(this).attr("placeholder");
            return $(this).attr("placeholder", " ");
        });
        $("input[type=text],input[type=email],input[type=password]").blur(function () {
            if ($(this).val() === "") {
                return $(this).attr("placeholder", placeholder);
            }
        });


        $("#save-btn").children("a").click(function () {
            $("#ajax_loader").show();
            $(".shadow").show();
            $.post($(this).parents("form").attr("action"), $(this).parents("form").serialize(), (function (response) {
                if (response.success) {
                    window.location.href = response.url
                } else {
                    $("#errors").html(response.html);
                    $("#ajax_loader").hide();
                    $(".shadow").hide();
                }

            }), "json");
            return false;

        });

    });


</script>