config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :confirmation => "users/confirmations",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :unlocks => "users/unlocks",
      :omniauth_callbacks => "users/omniauth_callbacks"
  }

  devise_scope :user do
    get "sign_in" => "users/sessions#new"
    get "sign_up" => "users/registrations#new"
    get "sign_out" => "users/sessions#destroy"
    get "change_password" => "users/registrations#change_password"
    post "update_password" => "users/registrations#update_password"
    get "/super_admin" => "users/sessions#super_admin_new"
  end

  root :to => "home#index"

  resources :home

  namespace :super_admin do
    resources :dashboard
    resources :categories
    resources :sub_categories
  end

end

app/controllers/super_admin/sub_categories_controller.rb
class SuperAdmin::SubCategoriesController < SuperAdmin::SuperAdminController
  add_breadcrumb "SUB CATEGORIES", "/super_admin/sub_categories"
  layout "super_admin"

  def index
    @sub_categories = Category.where("parent_id IS NOT NULL")
  end

  def new
    @category = Category.new
    #render :layout => false
  end

  def create
    @category = Category.new(category_params)
    unless params[:category][:parent_id].blank?
      if @category.save
        flash[:notice] = "Sub Category was successfully Added."
        render :json => {:success => true, :url => super_admin_sub_categories_path}.to_json
      else
        @errors = @category.errors
        render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      end
    else
      @category.errors.add(:parent_category, "Can't be Blank")
      @errors = @category.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def update
    @category = Category.find_by_id(params[:id])
    unless params[:category][:parent_id].blank?
      if @category.update_attributes(category_params)
        flash[:notice] = "Category was successfully Added."
        render :json => {:success => true, :url => super_admin_sub_categories_path}.to_json
      else
        @category = @user.errors
        render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
      end
    else
      @category.errors.add(:Parent_category, "Can't be Blank")
      @errors = @category.errors
      render :json => {:success => false, :html => render_to_string(:partial => '/layouts/errors')}.to_json
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
    #render :layout => false
  end

  def category_params
    params.require(:category).permit(:name, :parent_id, :parent_type)
  end


end

app/views/super_admin/customers/sub_categories/_form.html.erb
<div class="row" id="errors"></div>
<section class="g_inputs_phold" style="float: left;width: 48%; margin: 30px 0px">

  <div class="g_inputitem">
    <%= f.select :parent_id, Category.where(:parent_id => nil).all.map { |cat| [cat.name, cat.id] }, {include_blank: 'Select Parent Category'} %>
  </div>
  <div class="g_inputitem">
    <%= f.text_field :name, :placeholder => "SUB CATEGORY NAME" %>
  </div>

</section>

<!--g_inputs_phold ends-->
<div class="g_popup_head_bot"></div>
<!--g_popup_head ends-->
<div class="g_popup_bot_btns">
  <div class="pl_btn1" id="cancel-btn">
    <a href="javascript:void(0);">CANCEL</a>
  </div>
  <!--pl_btn1 ends-->
  <div class="p2_btn1" id="save-btn">
    <a href="javascript:void(0);">SAVE CHANGES</a>
  </div>
  <!--p2_btn1 ends-->
</div>

app/views/super_admin/customers/sub_categories/_list.html.erb
<table class="table table-striped table-bordered table-hover" id="sub_category_table">
  <thead>
  <tr>
    <th>
      Name
    </th>
    <th>
      Parent Category
    </th>
    <th>
      Sub Category Item Count
    </th>
    <th>
      Created
    </th>
    <th style="width: 120px">
      Action
    </th>
  </tr>
  </thead>
  <% unless @sub_categories.blank? %>
      <tbody>
      <% @sub_categories.each_with_index do |sub_category, index| %>
          <tr class="odd gradeX">

            <td>
              <%= sub_category.name %>
            </td>
            <td>
              <%= sub_category.parent.name %>
            </td>
            <td class="center">
              <%= sub_category.items.size %>
            </td>
            <td class="center">
              <%= sub_category.created_at.strftime("%m-%d-%Y  %H:%M:%S %p") %>
            </td>
            <td>
              &nbsp;&nbsp;&nbsp;
              <%= link_to "Edit", edit_super_admin_sub_category_path(sub_category.id), :style => "text-decoration:none" %>
              &nbsp;&nbsp;&nbsp;

              <%= link_to "View", super_admin_sub_category_path(sub_category.id), :style => "text-decoration:none" %>
            </td>
          </tr>
      <% end %>
      </tbody>
  <% end %>
</table>

app/views/super_admin/customers/sub_categories/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
      Manage Sub Categories
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="/super_admin/dashboard">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="/super_admin/customers">Edit Sub Categories</a>
      </li>

    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
  <div class="col-md-6 ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i> Edit Sub Categories
        </div>
        <div class="tools">
          <a class="collapse" href="">
          </a>

        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for(@category, :url => {:controller => "super_admin/sub_categories", :action => "update"}, :method => "put") do |f| %>
            <%= f.hidden_field :parent_type, :value => "Category" %>
            <div class="form-body">
              <div class="row" id="errors"></div>
              <div class="form-group">
                <label>Parent Category</label>

                <div class="input-group">
                  <%= f.select :parent_id, Category.where(:parent_id => nil).all.map { |cat| [cat.name, cat.id] }, {include_blank: 'Select Parent Category'}, :class => "form-control" %>
                </div>
              </div>
              <div class="form-group">
                <label>Name</label>

                <div class="input-group">
                  <%= f.text_field :name, :autofocus => true, :class => "form-control", :placeholder => "Name" %>
                </div>
              </div>
            </div>
            <div class="form-actions">
              <div class="z_100" id="save-btn">
                <a class="btn blue" href="javascript:void(0)">Save</a>
              </div>
              <!--<button class="btn blue" type="submit">Update</button>-->
              <%#= f.submit "Save", :class => "btn blue" %>
            </div>
        <% end %>
      </div>
    </div>
    <!-- END SAMPLE FORM PORTLET-->

  </div>
</div>

<div class="clearfix">
</div>

</div>


<script type="text/javascript">

    $(document).ready(function () {

        var placeholder = " ";
        $("input[type=text],input[type=email],input[type=password]").focus(function () {
            placeholder = $(this).attr("placeholder");
            return $(this).attr("placeholder", " ");
        });
        $("input[type=text],input[type=email],input[type=password]").blur(function () {
            if ($(this).val() === "") {
                return $(this).attr("placeholder", placeholder);
            }
        });


        $("#save-btn").children("a").click(function () {
            $("#ajax_loader").show();
            $(".shadow").show();
            $.post($(this).parents("form").attr("action"), $(this).parents("form").serialize(), (function (response) {
                if (response.success) {
                    window.location.href = response.url
                } else {
                    $("#errors").html(response.html);
                    $("#ajax_loader").hide();
                    $(".shadow").hide();
                }

            }), "json");
            return false;

        });

    });


</script>

app/views/super_admin/customers/sub_categories/index.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
      Sub Categories
      <small>Edit , View and More</small>
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="/super_admin/dashboard">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="/super_admin/customers">All Sub Categories</a>
        <!--<i class="fa fa-angle-right"></i>-->
      </li>
    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box grey-cascade">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-globe"></i>Current Sub Categories
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
          <a href="#portlet-config" data-toggle="modal" class="config">
          </a>
          <a href="javascript:;" class="reload">
          </a>
          <a href="javascript:;" class="remove">
          </a>
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-toolbar">
          <div class="btn-group">
            <%= link_to(new_super_admin_sub_category_path) do %>
                <button id="sample_editable_1_new" class="btn green">
                  Add New <i class="fa fa-plus"></i>
                </button>
            <% end %>
          </div>

        </div>
        <div id="sub_category_lis">
          <%= render :partial => "super_admin/sub_categories/list" %>
        </div>
      </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
  </div>
</div>

<!-- END PAGE CONTENT-->
</div>
</div>


<script>
    jQuery(document).ready(function () {
        TableManaged.init();
        initialize_table();
    });

    function initialize_table() {
        var active_table = $('#sub_category_table');

        // begin first table
        active_table.dataTable({
            "columns": [
                {
                    "orderable": true
                },
                {
                    "orderable": true
                },
                {
                    "orderable": true
                },
                {
                    "orderable": true
                },
                {
                    "orderable": false
                }


            ],
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 5,
            "pagingType": "bootstrap_full_number",
            "language": {
                "lengthMenu": "_MENU_ records",
                "paginate": {
                    "previous": "Prev",
                    "next": "Next",
                    "last": "Last",
                    "first": "First"
                }
            },
            "columnDefs": [
                {  // set default column settings
                    'orderable': false,
                    'targets': [0]
                },
                {
                    "searchable": false,
                    "targets": [0]
                }
            ],
            "order": [
                [1, "asc"]
            ] // set first column as a default sort by asc
        });

    }


</script>

app/views/super_admin/customers/sub_categories/new.erb
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
    <h3 class="page-title">
      Manage Sub Categories
    </h3>
    <ul class="page-breadcrumb breadcrumb">
      <li>
        <i class="fa fa-home"></i>
        <a href="/super_admin/dashboard">Home</a>
        <i class="fa fa-angle-right"></i>
      </li>
      <li>
        <a href="/super_admin/customers">Sub Categories</a>
      </li>

    </ul>
    <!-- END PAGE TITLE & BREADCRUMB-->
  </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
  <div class="col-md-6 ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i> Create New Sub Categories
        </div>
        <div class="tools">
          <a class="collapse" href="">
          </a>

        </div>
      </div>
      <div class="portlet-body form">
        <%= form_for(@category, :url => {:controller => "super_admin/sub_categories", :action => "create"}, :method => "post") do |f| %>
            <%= f.hidden_field :parent_type, :value => "Category" %>
            <div class="form-body">
              <div class="row" id="errors"></div>
              <div class="form-group">
                <label>Parent Category</label>

                <div class="input-group">
                  <%= f.select :parent_id, Category.where(:parent_id => nil).all.map { |cat| [cat.name, cat.id] }, {include_blank: 'Select Parent Category'}, :class => "form-control" %>
                </div>
              </div>
              <div class="form-group">
                <label>Name</label>

                <div class="input-group">
                  <%= f.text_field :name, :autofocus => true, :class => "form-control", :placeholder => "Name" %>
                </div>
              </div>
            </div>
            <div class="form-actions">
              <div class="z_100" id="save-btn">
                <a class="btn blue" href="javascript:void(0)">Save</a>
              </div>
              <!--<button class="btn blue" type="submit">Update</button>-->
              <%#= f.submit "Save", :class => "btn blue" %>
            </div>
        <% end %>
      </div>
    </div>
    <!-- END SAMPLE FORM PORTLET-->

  </div>
</div>

<div class="clearfix">
</div>

</div>


<script type="text/javascript">

    $(document).ready(function () {

        var placeholder = " ";
        $("input[type=text],input[type=email],input[type=password]").focus(function () {
            placeholder = $(this).attr("placeholder");
            return $(this).attr("placeholder", " ");
        });
        $("input[type=text],input[type=email],input[type=password]").blur(function () {
            if ($(this).val() === "") {
                return $(this).attr("placeholder", placeholder);
            }
        });


        $("#save-btn").children("a").click(function () {
            $("#ajax_loader").show();
            $(".shadow").show();
            $.post($(this).parents("form").attr("action"), $(this).parents("form").serialize(), (function (response) {
                if (response.success) {
                    window.location.href = response.url
                } else {
                    $("#errors").html(response.html);
                    $("#ajax_loader").hide();
                    $(".shadow").hide();
                }

            }), "json");
            return false;

        });

    });


</script>